FROM python:3.10-slim

WORKDIR /opt/scripts

COPY ./dags/scripts /opt/scripts
COPY ./data /data

# Install clickhouse driver
RUN pip install clickhouse-driver

# Run script once
CMD ["python", "ingest_continuous_data.py"]
