FROM python:3.10-slim

WORKDIR /opt/scripts

COPY ./dags/scripts/ingest_daily_data.py /opt/scripts/
COPY ./data /data

# Install clickhouse driver
RUN pip install clickhouse-driver

# Run daily ingestion script
CMD ["python", "ingest_daily_data.py"]